const FIELDS: Record<string, { label: string }> = {
  password: { label: 'Пароль' },
  login: { label: 'Логин' },
  vpn: { label: 'VPN' },
  ip: { label: 'IP' },
  mac: { label: 'MAC адрес' },
  wifiName1: { label: 'Название WIFI Сети 1' },
  wifiName2: { label: 'Название WIFI Сети 2' },
  wifiPassword1: { label: 'Пароль WIFI Сети 1' },
  wifiPassword2: { label: 'Пароль WIFI Сети 2' },
  wifiFreq1: { label: 'Частота WIFI Сети 1' },
  wifiFreq2: { label: 'Частота WIFI Сети 2' },
  purposePort: { label: 'Назначение/Порт' },
  providerName: { label: 'Провайдер' },
  contactNumber: { label: 'Контактный номер' },
  numberOfContract: { label: 'Номер договора' },
  gateway: { label: 'Основной шлюз' },
  subnetMask: { label: 'Маска подсети' },
  dns1: { label: 'DNS 1' },
  dns2: { label: 'DNS 2' },
  connectionType: { label: 'Тип подключения' },
  purpose: { label: 'Назначение' },
  model: { label: 'Модель' },
  serialNumber: { label: 'Серийный номер' },
  camerasConnected: { label: 'Камер подключено' },
  innerIp: { label: 'Внутренний IP' },
  outerIp: { label: 'Внешний IP' },
  port: { label: 'Порт' },
  hdd: { label: 'HDD' },
  number: { label: 'Номер' },
  name: { label: 'Название' },
  inventoryNumber: { label: 'Инвентарный номер / Имя ПК' },
  os: { label: 'ОС' },
  activationKey: { label: 'Ключ активации' },
  fduLicense: { label: 'Лицензия FDU' },
  anyDeskId: { label: 'AnyDesk ID' },
  anyDeskPass: { label: 'AnyDesk Pass' },
  domain: { label: 'Домен' },
  znkkm: { label: 'ЗН ККМ' },
  rnmkkm: { label: 'РНМ ККМ' },
  user: { label: 'Пользователь' },
  phone: { label: 'Телефон' },
  teamViewer: { label: 'TeamViewer' },
  adtvPassword: { label: 'Пароль AD/TV' },
  adminPassword: { label: 'Пароль админа' },
  productKey: { label: 'Ключ продукта' },
  operatorName: { label: 'Оператор' },
  innerNumber: { label: 'Внутренний номер' },
  subId: { label: 'ID абонента' },
  sourceProxy: { label: 'Исходящий прокси' },
};

export default FIELDS;
